name: Checkout Code with Submodules

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: recursive
