name: Build Platforms

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Checkout Submodules
      shell: bash
      run: |
        git submodule sync
        git submodule update --init --recursive --depth=2
    
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '12.x' 

