name: Build with Dotnet

on: [workflow_dispatch]

permissions:
  contents: write
  packages: write  
  deployments: write

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Checkout submodules
        run: |
          cd ${{ github.workspace }}
          git submodule sync
          git submodule update --init --recursive --depth=1

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            2.1.x
            3.1.x
            6.0.x
            7.0.x
            8.0.x

      - name: Build all solutions
        run: |
          # Set the root directory to search for .sln files
          $rootDirectory = $env:GITHUB_WORKSPACE
        
          # Get all .sln files recursively
          $slnFiles = Get-ChildItem -Path $rootDirectory -Filter "*.sln" -File -Recurse
          
          # Loop through each .sln file and call dotnet build
          foreach ($slnFile in $slnFiles) {
              Write-Host "Building $($slnFile.FullName)"
              cd $slnFile.Directory.FullName
              dotnet build
          }
        
