name: Build with Dotnet

on: [workflow_dispatch]

permissions:
  contents: write
  packages: write  
  deployments: write

defaults:
  run:
    shell: pwsh

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: |
          cd ${{ github.workspace }}
          git submodule sync
          git submodule update --init --recursive --depth=1

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            2.1.x
            3.1.x
            6.0.x
            7.0.x
            8.0.x
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
      
          # Restore the application to populate the obj folder with RuntimeIdentifiers
      - name: Restore the application
        run: |
          # Set the root directory to search for .sln files
          $rootDirectory = $env:GITHUB_WORKSPACE
        
          # Get all .sln files recursively
          $slnFiles = Get-ChildItem -Path $rootDirectory -Filter "*.sln" -File -Recurse
          
          # Loop through each .sln file and call dotnet build
          foreach ($slnFile in $slnFiles) {
              Write-Host "Building $($slnFile.FullName)"
              msbuild $slnFile /t:Restore /p:Configuration=$env:Configuration
          }
        env:
          Configuration: ${{ matrix.configuration }}
        
